version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
