---
version: "3.6"

services:
  cypress:
    image: sirius/end-to-end-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./cypress:/root/cypress"
      - "./cypress.json:/root/cypress.json"
      - "./test-results:/test-results"
    command: [ "--headless", "-b", "chrome"]

networks:
  default:
    external: true
    name: opg-sirius_default
