---
version: "3.6"

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "--headless", "-b", "chrome"]
    volumes:
      - "./cypress:/root/cypress"

networks:
  default:
    external: true
    name: opg-sirius_default
