---
version: "3.6"

services:
  cypress:
    image: sirius/end-to-end-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        CYPRESS_BASE_URL: https://development.sirius.opg.service.justice.gov.uk
    volumes:
      - "./cypress:/home/node/cypress"
      - "./cypress.config.js:/home/node/cypress.config.js"
      - "./test-results/logs:/home/node/cypress/logs"
      - "./test-results/screenshots:/home/node/cypress/screenshots"
      - "./test-results:/test-results"
